### ISSUE TITLE
Create a yaml parser to random forest features

### ISSUE THREAD

**Issue by LeoSilvaGomes** [PDA-FGA/Playground#16]
## Description
 Create yaml parser to support random forest features

### Output

- **dataframe:** data with the column to be predicted if is keyboard smash or not
- **output_folder**
- **output_prefix**
- **data_lang**
- **dimensions**
- **enabled_features:** word_embedding | ksmash_sequence_vowels | ksmash_sequence_consonants | ksmash_sequence_special_characters | ksmash_numbers | ksmash_char_frequence

#### Yaml structure
```
- feature_engineering
  - input:
    - columns:
      - [column_name', 'column_name']: ${feature_input_alias}
      - 'column_name': ${feature_input_alias}
    - features:
      - 'word_embedding':
        - 'off'
        - data_lang: 'es'
        - ${feature_input_alias}:
          - dimensions: 25
      - 'keyboard_smash':
        - ksmash_sequence_vowels: 'off'
```

**Comment by LeoSilvaGomes** [comment]
### Yaml structure


#### Proposta 1
```
- model
   - random_forest
     - feature_engineering
       - columns: 
         - 'column_name'
         - 'column_name'
       - ignore: 
          - char_frequency
          - special_character_sequency
          - number_sequency
          - vowels_sequency
          - consoants_sequency
```

#### Proposta 2
```
- feature_engineering
  - feature name *** (sentence_validation)
   - columns:
     -  [column_name', 'column_name']
     - 'column_name'
   - ignore: 
      - char_frequency
      - special_character_sequency
      - number_sequency
      - vowels_sequency
      - consoants_sequency
    
- model
   - random_forest
     - feature_engineering
       - feature name *** (sentence_validation)
         - ignore: 
            - char_frequency
            - special_character_sequency
            - number_sequency
            - vowels_sequency
            - consoants_sequency
```

#### Proposta 3 ✨ 
```
- feature_engineering
  - keyboard_smash
   - columns:
     -  [column_name', 'column_name']
     - 'column_name'
    
- model
   - random_forest
```

**Comment by LeoSilvaGomes** [comment]
### Proposta 4 ✨ 

```
- feature_engineering
  - input:
    - columns:
      - [column_name', 'column_name']: ${feature_input_alias}
      - 'column_name': ${feature_input_alias}
    - features:
      - 'word_embedding':
        - data_lang: 'es'
        - ${feature_input_alias}:
          - dimensions: 25
      - 'keyboard_smash'
         
- model
  - random_forest
    - type: 'address'
    - thresholds:
      - test_size: 0.3
      - n_estimators: 100
      - keyboard_smash:
      - ${feature_input_alias}
        - ksmash_sequence_vowels: 1.00
        - ksmash_sequence_consonants: 1.999
        - ksmash_sequence_special_characters: 2.2499
        - ksmash_numbers: 2.9
        - ksmash_char_frequence: 2.78
```
