### ISSUE TITLE
Create a yaml parser random forest address model 

### ISSUE THREAD

**Issue by LeoSilvaGomes** [PDA-FGA/Playground#18]
### Description
 Create yaml parser to support random forest address model

### Output

- **type**
- **thresholds:**
  - test_size
  - n_estimators
  - keyboard_smash

#### Yaml structure
```    
- model
  - random_forest
    - type: 'address'
    - thresholds:
      - test_size: 0.3
      - n_estimators: 100
      - keyboard_smash:
        - ${feature_input_alias}
          - ksmash_sequence_vowels: 1.00
          - ksmash_sequence_consonants: 1.999
          - ksmash_sequence_special_characters: 2.2499
          - ksmash_numbers: 2.9
          - ksmash_char_frequence: 2.78
```
